### ISSUE TITLE
Double click node cannot expand.

### ISSUE THREAD

**Issue by Fangyh09** [Neilos/bihisankey#13]
I  double clicked node but it cannot expand. Thanks~

**Comment by duhaime** [comment]
To follow up on @Fangyh09's comment, the doubleclick event seems to run fine in recent Firefox, but not recent Chrome or Safari.

**Comment by aherve** [comment]
Not sure what the problem is, but I played around with the script, and it seems that the function `dragmove` prevents the click events from firing.

If you comment the `.on("drag", dragmove)` section, then double click works as expected

**Comment by duhaime** [comment]
@Fangyh09 @aherve This happens in the example on bl.ocks.org because that example [re-appends a dragged node to its parent on drag start](https://gist.github.com/Neilos/584b9a5d44d5fe00f779#file-app-js-L410), which effectively removes the double-click event listener. You can fix this problem and enable drag by removing that line, as I've done here: http://bl.ocks.org/duhaime/3865371eea1bd32b36f53e63dabb6b72

**Comment by aherve** [comment]
@duhaime Nice !

**Comment by Fangyh09** [comment]
@duhaime Thanks!
