### ISSUE TITLE
How can I customize the node shape from rectangle?

### ISSUE THREAD

**Issue by mkpasala** [Neilos/bihisankey#17]
I want to customize the node shape from default rectangle to my own custom shape for example Right Chervon.

**Comment by mkpasala** [comment]
#[https://www.wikibudgets.org/sankey?id=2gamvvoaf](url)

**Comment by Neilos** [comment]
I'm really sorry, but it's been 4 years since I wrote this library, and I can barely remember how any of it works. That is why this library is no longer maintained.

The shape itself is not hard coded into the library so you may be able to configure it. The example app.js file I provided may provide some clues. In particular look for `.select("rect")` and see if you can replace them with an svg path for the Chevron shape (you'll also need to amend the attributes accordingly). For example, check out [this line](https://gist.github.com/Neilos/584b9a5d44d5fe00f779#file-app-js-L315) in the gist provided.
